import { chromium } from '../../.preview-tools/node_modules/playwright-core/index.mjs';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:810},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:4173/');
await page.waitForTimeout(3500);
await mkdir('test-results',{recursive:true});
await page.screenshot({path:'test-results/orbit.png'});
console.log(JSON.stringify({errors,fps:await page.locator('#universe').getAttribute('data-fps')},null,2));
await page.locator('#cinema-button').click();
await page.locator('#front-view').click();
await page.waitForTimeout(600);
await page.locator('#cinema-button').click();
await page.screenshot({path:'test-results/front.png'});
await page.locator('#universe').click({position:{x:100,y:100}});
await page.keyboard.press('r');
await page.mouse.move(600,400);await page.mouse.down();await page.mouse.move(800,510,{steps:12});await page.mouse.up();
await page.waitForTimeout(600);
await page.screenshot({path:'test-results/rotated.png'});
await page.mouse.wheel(0,-240);await page.waitForTimeout(300);
await page.mouse.click(1000,500);await page.waitForTimeout(250);
await page.screenshot({path:'test-results/wave.png'});
console.log(JSON.stringify({status:await page.locator('#status').textContent(),errors},null,2));
assert.equal(await page.locator('#status').textContent(),'已激发曲面引力波纹');
await page.keyboard.press('r');
await page.keyboard.press('Space');
const beforePan=await page.screenshot();
await page.keyboard.down('Shift');
await page.mouse.move(600,400);await page.mouse.down();await page.mouse.move(700,440,{steps:8});await page.mouse.up();
await page.keyboard.up('Shift');await page.waitForTimeout(350);
assert(!beforePan.equals(await page.screenshot()),'Panning must change the image');
await page.locator('#cinema-button').click();
await page.locator('#top-view').click();
assert.equal(await page.locator('#top-view').getAttribute('aria-pressed'),'true');
await page.locator('#cinema-button').click();
await page.screenshot({path:'test-results/top.png'});
await page.setViewportSize({width:390,height:844});
await page.mouse.click(50,50);await page.keyboard.press('r');
await page.waitForTimeout(500);
await page.screenshot({path:'test-results/mobile.png'});
assert.equal(await page.locator('body').evaluate(e=>e.scrollWidth),390);
console.log('Orbit, front, top, wave, pan and mobile layout checks passed.');
await browser.close();
if(errors.length)process.exitCode=1;
