// Compiled by MathJax at build time, not assembled from Unicode symbols.
export const formulasTex = [
  String.raw`G_{\mu\nu}+\Lambda g_{\mu\nu}=\frac{8\pi G}{c^4}T_{\mu\nu}`,
  String.raw`S_{\mathrm{BH}}=\frac{k_{\mathrm B}c^3 A}{4G\hbar}`,
  String.raw`T_{\mathrm H}=\frac{\hbar c^3}{8\pi GMk_{\mathrm B}}`,
  String.raw`r_{\mathrm s}=\frac{2GM}{c^2}`,
  String.raw`i\hbar\frac{\partial\Psi}{\partial t}=-\frac{\hbar^2}{2m}\nabla^2\Psi+V\Psi`,
  String.raw`\Delta x\,\Delta p\geq\frac{\hbar}{2}`,
  String.raw`E^2=p^2c^2+m^2c^4`,
  String.raw`S=k_{\mathrm B}\ln\Omega`,
  String.raw`\nabla\cdot\mathbf E=\frac{\rho}{\varepsilon_0}`,
  String.raw`\nabla\times\mathbf E=-\frac{\partial\mathbf B}{\partial t}`,
  String.raw`\nabla\times\mathbf B=\mu_0\mathbf J+\mu_0\varepsilon_0\frac{\partial\mathbf E}{\partial t}`,
  String.raw`\nabla\cdot\mathbf B=0`,
  String.raw`\frac{\partial\rho}{\partial t}+\nabla\cdot(\rho\mathbf v)=0`,
  String.raw`\nabla^2\Phi=4\pi G\rho`,
  String.raw`\hat H\lvert\psi_n\rangle=E_n\lvert\psi_n\rangle`,
  String.raw`e^{i\pi}+1=0`,
  String.raw`\hbar=\frac{h}{2\pi}`,
  String.raw`\Omega^2=\frac{GM}{r^3}`,
  String.raw`F=\frac{Gm_1m_2}{r^2}`,
  String.raw`E=mc^2`,
  String.raw`\oint_{\partial S}\mathbf F\cdot\mathrm d\mathbf r=\iint_S(\nabla\times\mathbf F)\cdot\mathrm d\mathbf S`,
  String.raw`\Gamma(z)=\int\nolimits_0^{+\infty}t^{z-1}e^{-t}\,\mathrm dt`,
  String.raw`\det(A-\lambda I)=0`,
  String.raw`\sum_{n=1}^{\infty}\frac{1}{n^2}=\frac{\pi^2}{6}`,
  String.raw`\mathrm dU=T\,\mathrm dS-p\,\mathrm dV`,
  String.raw`\mathrm ds^2=-c^2\mathrm dt^2+\mathrm dx^2+\mathrm dy^2+\mathrm dz^2`,
  String.raw`\mathcal L=\frac12m\dot q^2-V(q)`,
  String.raw`\frac{\mathrm d}{\mathrm dt}\left(\frac{\partial\mathcal L}{\partial\dot q}\right)-\frac{\partial\mathcal L}{\partial q}=0`,
  String.raw`[\hat x,\hat p]=i\hbar`,
  String.raw`pV=nRT`,
  String.raw`\Delta G=\Delta H-T\Delta S`,
  String.raw`c=2.99792458\times10^8\,\mathrm{m\,s^{-1}}`,
  String.raw`\hbar\omega=E_2-E_1`,
  String.raw`\frac{\partial^2u}{\partial t^2}=c^2\nabla^2u`,
  String.raw`\psi(x,t)=A e^{i(kx-\omega t)}`,
  String.raw`R_{\mu\nu}-\frac12R g_{\mu\nu}=\kappa T_{\mu\nu}`,
  String.raw`f(x)=\frac{1}{2\pi}\int\nolimits_{-\infty}^{+\infty}\hat f(k)e^{ikx}\,\mathrm dk`,
  String.raw`\int\nolimits_{\mathbb R^3}|\Psi|^2\,\mathrm d^3x=1`,
  String.raw`\lambda=\frac{h}{p}`,
  String.raw`\hbar=1.054571817\times10^{-34}\,\mathrm{J\,s}`,
];
export const atlasIndices=Array.from({length:48},(_,i)=>(i*17)%formulasTex.length);
